name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  buf-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1
      - name: Buf Lint
        uses: bufbuild/buf-lint-action@v1
        with:
          input: proto

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Build
        run: |
          go test -v -short ./...
          go build cmd/ionscale/main.go