name: Integration Tests

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ts_version:
          - "v1.56"
          - "v1.54"
          - "v1.52"
          - "v1.50"
          - "v1.48"
          - "v1.46"
          - "v1.44"
          - "v1.42"
          - "v1.40"
    env:
      IONSCALE_TESTS_TS_TARGET_VERSION:  ${{ matrix.ts_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Run Integration Tests
        run: |
          go test -v ./tests