name: Integration Tests

on: workflow_dispatch

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ts_version:
          - "1.36.0"
          - "1.34.1"
          - "1.32.3"
          - "1.30.2"
          - "1.28.0"
          - "1.26.2"
          - "1.24.2"
    env:
      IONSCALE_TESTS_TS_TARGET_VERSION:  ${{ matrix.ts_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Run Integration Tests
        run: |
          go test -v ./tests