name: Integration Tests

on: workflow_dispatch

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ts_version:
          - "1.46.0"
          - "1.44.2"
          - "1.42.0"
          - "1.40.1"
          - "1.38.4"
          - "1.36.2"
          - "1.34.1"
    env:
      IONSCALE_TESTS_TS_TARGET_VERSION:  ${{ matrix.ts_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Run Integration Tests
        run: |
          go test -v ./tests